[package]
name = "wsio-server"
version = "0.11.0"

authors.workspace = true
categories.workspace = true
description = "Async WebSocket server framework for ws.io â€” provides event-based real-time messaging, namespaces, and room-like broadcasting."
edition.workspace = true
homepage.workspace = true
include = [
  "Cargo.toml",
  "README.md",
  "src/**/*",
]

keywords.workspace = true
license.workspace = true
readme = "./README.md"
repository.workspace = true

# Dependencies
[dependencies]
anyhow = "1.0.100"
arc-swap = "1.8.0"
futures-util = { version = "0.3.31", default-features = false }
http = "1.4.0"
http-body = "1.0.1"
hyper = "1.8.1"
hyper-util = { version = "0.1.19", features = ["tokio"] }
kikiutils = { version = "0.7.2", features = ["atomic-enum-cell", "fx-collections"] }
num_enum = "0.7.5"
parking_lot = "0.12.5"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["macros", "rt", "sync", "time"] }
tokio-tungstenite = { version = "0.28.0", default-features = false, features = ["handshake"] }
tokio-util = "0.7.18"
tower-layer = { version = "0.3.3", optional = true }
tower-service = { version = "0.3.3", optional = true }
wsio-core = { path = "../wsio-core", version = "0.12.0" }
url = "2.5.7"

# Features
[features]
## Define features
connection-extensions = []
packet-codec-cbor = ["wsio-core/packet-codec-cbor"]
packet-codec-msgpack = ["wsio-core/packet-codec-msgpack"]
packet-codec-postcard = ["wsio-core/packet-codec-postcard"]
packet-codec-sonic-rs = ["wsio-core/packet-codec-sonic-rs"]
tower = [
  "dep:tower-layer",
  "dep:tower-service",
]

## Default and alias
default = []
all = [
  "connection-extensions",
  "packet-codec-cbor",
  "packet-codec-msgpack",
  "packet-codec-postcard",
  "packet-codec-sonic-rs",
  "tower",
]

full = ["all"]
